# ---------- Stage 1: Build Frontend ----------
FROM node:20-alpine AS builder

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .

RUN npm run build

# ---------- Stage 2: Serve with Nginx ----------
FROM nginx:alpine

# React génère un dossier build et non dist
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]